# Example: archive in a local filesystem
[global]

[source.data-root]
path = "/media/rootdisk/_btrbk_snap"
# patterns are not matched against the timestamp suffix part.
# "*" "?" wildcard supported. Specifying multiple patterns will backup the union of the them.
filter = ["*"]


[dest.local-dir]
# a "dest" block, specifying backup location

# driver: the type of the storage backend.
# "local" means or local filesystem. Other options are "s3" "gcs"
driver = "local"
# path: a directory-ish in filesystem or bucket-ish. Must be absolute path.
path = '/media/sata-256g/bbkar-temp/'


[sync.1]
# a "sync" block connects a source to a dest
source = "data-root"
dest = "local-dir"

# setting "filter" here to limit the subvolumes to sync.
# defaults to be ['*'], meaning all subvolumes from the source
# This option is applied after the source's "filter" option.
